package learnings.exceptions;

public class MainClass2 {

	void databaseActivity() {
		
		try {
		
			// establish the connection
			// do the activity
			
			
		} catch(Exception e) {
			// i caught an exception! i saved my code from crashing!
			
		} finally {
			// close the connection
		}
	}
	
	
	public static void main(String[] args) {
		
		

	}

}
